In [ ]:
import torch
import pandas
import numpy as np

In [105]:
training_data = torch.from_numpy(pandas.read_csv("data/train.csv").to_numpy()).T
test_data = torch.from_numpy(pandas.read_csv("data/test.csv").to_numpy()).T

In [106]:
m,n = training_data.shape

X_train = (training_data[1:n,:] / 255)
Y_train = torch.eye(10)[training_data[0,:]]


In [116]:
X_train[:,0].reshape(28,28)
kernel = torch.tensor([
    [1,1,1],
    [0,0,0],
    [-1,-1,-1]
]).float()
    

In [ ]:
class CNN:
    def __init__(self):
        self.conv_weight = torch.randn(4,1,3,3)
        self.conv_bias = torch.zeros(4)

    def patch_generator(index, kernel_size, kernel):
        image = X_train[:,index].reshape(28,28)
        image_h, image_w = image.shape
        for h in range(image_h-kernel_size+1):
            for w in range(image_w-kernel_size+1):
                patch = image[h:(h+kernel_size), w:(w+kernel_size)]
                print(patch)
                yield patch @ kernel
                
        


In [ ]:
results = list(CNN.patch_generator(1, 3, kernel))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0